[package]
name = "m17"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
clap = { version = "4", features = ["derive"] }
codec2 = "0.3"
futuresdr = { path = "../..", features = ["audio", "seify", "soapy"] }
wav = "1"
