[package]
name = "androidhw"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
futuresdr = { path = "../..", features = ["soapy"] }
jni = { version = "0.21" }
